services:

  mariadb:
    image: mariadb:11.8.2
    container_name: mariadb
    restart: unless-stopped
    env_file:
      - ./env/mariadb.env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      backend:
    ports:
      - "10.1.1.1:3306:3306"

  gogs:
    image: gogs/gogs:0.13.3
    container_name: gogs
    restart: unless-stopped
    volumes:
      - gogs:/data
    networks:
      backend:
    ports:
      - "22:22"
      - "10.1.1.1:8001:3000"
    depends_on:
      - mariadb

  dozzle:
    image: amir20/dozzle:v8.13.7
    container_name: dozzle
    restart: unless-stopped
    env_file:
      - ./env/dozzle.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      backend:
    ports:
      - "10.1.1.1:8002:8080"

  nginx:
    image: nginx:1.29
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      frontend:
    ports:
      - "10.1.1.1:80:80"

volumes:
  mariadb:
  gogs:
  
networks:
  backend:
    driver: bridge
    enable_ipv6: false
    ipam:
      config:
        - subnet: 10.1.1.0/24
